### ISSUE TITLE
Support Read the Docs Community & for Business

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs-preview#8]
Currently, the action only supports "Read the Docs Community". To support "Read for Business" we will need to think about:

- the combination of the project's slug + organization's slug
- the hard coded `org.readthedocs.build` domain

Reference: https://github.com/readthedocs/readthedocs.org/pull/9450#discussion_r929260239

**Comment by humitos** [comment]
This should be done in c70557245b0ae077da1a8aeef7f259e88f2916f6 but I haven't tested it yet. It should be used as:

```yaml
jobs:
  documentation-links:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/readthedocs-preview@main
        with:
          project-slug: "organization-project"
          platform: "business"
```
